### ISSUE TITLE
Transition to TS

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#10]
People told me you should not use JS in 2023.

It should be possible and maybe not even that hard to convert the entire Quasar app to TS.

**Comment by user411** [comment]
I will work on this today

**Comment by ebrakke** [comment]
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type is a pretty good middle ground IMO as it doesn't require any build changes, and has excellent support in VSCode. 
Biggest downside of typescript is just the build processes needed to actually support it, and certain libraries not playing nicely with typescript.

But at the same time, I love me some typescript.

**Comment by callebtc** [comment]
@user411 any news kind ser?
