### ISSUE TITLE
Could not connect to mint. e.keys.find is not a function

### ISSUE THREAD

**Issue by rossbates** [cashubtc/cashu.me#130]
I started by adding 8333.space:3338 as a mint. I was able to receive and send.

I added a second mint (mint.mountainlake.io) - and after that I've been unable to change mints without getting the error

`Could not connect to mint. e.keys.find is not a function`

I added a 3rd mint (https://mint.minibits.cash/Bitcoin) to test, and once it became the default, I could not switch out of that one.

Attaching a video to demonstrate behavior.

https://github.com/cashubtc/cashu.me/assets/103388/2d9621d2-017b-4a8e-aa5b-7023465b3547

**Comment by callebtc** [comment]
Hey there, someone else also reported this same issue. I don't know how to reproduce it yet, it sounds to me like a network error but I'm not sure. Are you able to step through the code to see where the error is thrown? My guess is it's somewhere in `fetchMintKeys`. It would be super helpful if you could help figure out where exactly this error happens.

**Comment by rossbates** [comment]
This is where the error fires when attempting to change mints. Is this helpful at all? If there's anything else I can provide from the debugger let me know.

![screenshot_2024-05-14_08 07 28@2x](https://github.com/cashubtc/cashu.me/assets/103388/5e54cc11-7546-4577-adc2-b76ded81c3db)

**Comment by callebtc** [comment]
Fixed in https://github.com/cashubtc/cashu.me/pull/147
