### ISSUE TITLE
Creating invoice button in Lightning receive should have a spinner while blocked

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#137]
Add a spinner to the button

**Comment by sepiropht** [comment]
Maybe I'm wrong, but isn't it already the case ? 

When  i do this:  
`  data: function () {
    return {
      createInvoiceButtonBlocked: true, //default is false
    };
  },
`


I go this  

![Capture d’écran du 2024-05-23 16-52-21](https://github.com/cashubtc/cashu.me/assets/3449108/ae0ff0a1-9a4f-4e61-9d6f-da6a81873dd8)
 
The spinner is already there

**Comment by callebtc** [comment]
Yes, is completed!
