### ISSUE TITLE
Can't Install App With Vanadium on GrapheneOS

### ISSUE THREAD

**Issue by crimsonleaf363** [cashubtc/cashu.me#177]
I don't see "Install App" as an option in the hamburger menu. I'm using Vanadium on GrapheneOS. Is there a workaround or setting that needs to be changed?

**Comment by callebtc** [comment]
> I don't see "Install App" as an option in the hamburger menu. I'm using Vanadium on GrapheneOS. Is there a workaround or setting that needs to be changed?

I suggest to Google for "PWA Vanadium", you might figure out weather Vanadium supports PWAs
