### ISSUE TITLE
Pending Proofs. Payment Failed!

### ISSUE THREAD

**Issue by nathan-hughes7** [cashubtc/cashu.me#185]
My wallet suddenly stopped working for sending payments. It will receive lightning payments fine but if I try to send ecash or lightning payments it give the error "Proofs pending. Payment failed!". I am using the minibits mint. Not sure what other information is needed to diagnose the issue. The wallet stillshows the funds in my wallet but I can't send them out. I also tried restoring the wallet on eNuts app and it couldn't find any proofs. 
[IMG_1360.pdf](https://github.com/user-attachments/files/15536914/IMG_1360.pdf)

**Comment by callebtc** [comment]
Please give more information about what you did before this error appeared. Proofs pending is not an error, it means that you have in-flight payments that are still ongoing. The wallet however should not have selected these proofs for new transactions. Are you paying hodl invoices?

**Comment by nathan-hughes7** [comment]
Yes I did pay a few hodl invoices, that's when the problem started. That was about 2 days ago now. It seems like the wallet is not letting the payments fail and is not selecting other proofs since I have added sats that would not be included in the hodl payments.

**Comment by nathan-hughes7** [comment]
I reached out to the Minibits mint and it looks like it was an issue on their end with the payment stuck pending. Not sure if the wallet had anything to do with it or not. I was able to recover the funds.

**Comment by DireMunchkin** [comment]
I also have the same error. I've been unable to zap anybody or redeem my funds out of the wallet for 3 days. Not sure if I paid a hodl invoice, I may have. @nathan-hughes7 how did you end up resolving this?

**Comment by nathan-hughes7** [comment]
I reached out to the minibits mint on nostr and they were able to help me. For me it was an issue with the mint not the cashu wallet.

On Aug 2, 2024, at 4:24 PM, DireMunchkin ***@***.***> wrote:

﻿

I also have the same error. I've been unable to zap anybody or redeem my funds out of the wallet for 3 days. Not sure if I paid a hodl invoice, I may have. @nathan-hughes7<https://github.com/nathan-hughes7> how did you end up resolving this?

**Comment by DireMunchkin** [comment]
No, I gave up trying to recover them. I had some back and forth with the mint operator but wasn't able to resolve the issue.

**Comment by callebtc** [comment]
In the case of an unexpected error, for example in the LN node, the pending proofs can get stuck in the mint db (out of precaution). Generally speaking, it's safe to delete older pending proofs from the DB. I'm hoping that we will soon automate this process so the mint can get out of that state by itself.
