### ISSUE TITLE
[Bug] Could not verify proofs

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#19]
A very elusive bug that I can't reproduce

Setting up a safe testing environment: 

- Go to legend.lnbits.com – create a new wallet – go to extensions and enable Cashu - create two mints
- Open cashu.me in two different browsers (incognito mode for fresh state)
- Send funds between the two trying to reproduce the bug.
- If the bug occurs you still have access to your funds (since it's your own mint)

I can't reproduce the bug no matter what I try.

My gut feeling is that it happens when the user has multiple mints and switches back and forth between. It seems to happen especially during a mint-to-mint swap. The safest way to test this is to create two mints on LNbits (legend.lnbits.com) by yourself so you can't lose funds when you get the bug. You can delete the browser local storage to reset your wallet (funds will then disappear!). 

![image](https://user-images.githubusercontent.com/93376500/233940191-f56a19d2-72ca-45ad-8e8b-075fb49cb62f.png)

**Comment by callebtc** [comment]
User reports so far are sporadic. They all see to have one common denominator which is multiple mints. We had a similar bug before which was a race condition that happened when there was a invoice check worker running on `mint1` and the user tried to mint tokens at `mint2` at the same time. The worker would fetch the public keys of `mint1` (by activating it) but the minting routine on `mint2` would then falsely use the public keys of `mint1` and create tokens that are invalid (leading to "could not verify proofs" upon trying to spend them with `mint2`). We fixed this issue by fixing the public keys before any operation that uses `constructOutputs` so that they can't be overwritten by a routine running at the same time.

I will keep updating this list. Users reporting this bug said
- they used multi-mint swaps before
- they had one mint before, then received a token from a new mint

**Comment by callebtc** [comment]
Another user report: User had one mint in the wallet. User received ecash from a new mint, was asked if they trust the mint, received. When user tries to send funds, runs into "could not verify proofs" error.

**Comment by callebtc** [comment]
Setting up a safe testing environment: 

- Go to legend.lnbits.com – create a new wallet – go to extensions and enable Cashu - create two mints
- Open cashu.me in two different browsers (incognito mode for fresh state)
- Send funds between the two trying to reproduce the bug.
- If the bug occurs you still have access to your funds (since it's your own mint)

I can't reproduce the bug no matter what I try.

**Comment by callebtc** [comment]
Another user report: had funds on `mint1` and pressed "send ecash" and got 1 satoshi pending. Then initiated a swap from `mint1` to `mint2` (with no funds). The swap failed because they didn't have enough funds. Then something borked up (or maybe already before).

**Comment by ebrakke** [comment]
I was able to reproduce locally, though I still haven't figured out how to do it reliably.

The error is coming from the `splitApi` call when doing a mint swap. Digging in further to see if I can reproduce it reliably

**Comment by callebtc** [comment]
Oh my god

**Comment by ebrakke** [comment]
Yup! Here's a screen grab. I'm currently trying any number of combinations in an incognito window to see if I can get it happen in another environment. Let me know if there's data dumps that might be useful from this env that would help track it down and I can try to log those out!

https://user-images.githubusercontent.com/9901863/234280459-ad626803-4521-4713-b482-b7fa2c4cff16.mov

**Comment by callebtc** [comment]
The logs would be very useful to see if some operation is failing in the mean time. My guess is there is a race condition somewhere that breaks once the mints are switched during the swap. I couldn't reproduce this no matter how often I tried to swap. If you figure out how to get to this state, please let us know!

**Comment by ebrakke** [comment]
I think I can reliably reproduce it. This seems to work like 4 out of 5 times I tried it, but should help us narrow down to the root cause.
1) modify source code to set a breakpoint on the first line of `splitToSend` in `WalletPage.vue`

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9901863/234296615-0709e407-a643-4f0e-aa52-9bf74e368bed.png">

2) Start from a fresh wallet, and add 8333.space:3338 as a mint
3) Add another mint (I used https://legend.lnbits.com/cashu/api/v1/4gr9Xcmz3XEkUNwiBiQGoC)
4) Ensure dev tools is open (so the breakpoint will trigger)
5) Create an invoice for the lnbits mint and send `19` sats (not sure if the value is important, but was reliably able to do it with 19 sats)
6) Pay the invoice
7) Initiate a swap from lnbits to 8333.space. Important, this should trigger the breakpoint. When the breakpoint is triggered, refresh the page. This simulates a swap that doesn't end up going through for one reason or another, but the invoice stays as pending for that mint (I believe this is the important part)
8) After refresh, send 1 sat as ecash from the 8333 mint (breakpoint will trigger, just let it continue)
9) Try to redeem the ecash, you should see the error

https://user-images.githubusercontent.com/9901863/234296226-cce0ac27-975a-41b3-ae92-98a47634402d.mov

**Comment by cjbeery24** [comment]
Yeah, I was going to say, it looks like this error is generated here:
https://github.com/cashubtc/cashu-feni/blob/463b68bd4bea12560cb9f6b9a8782830df4c73e9/mint/mint.go#L299

This can happen during a Melt or Split API call:
https://github.com/cashubtc/cashu-feni/blob/463b68bd4bea12560cb9f6b9a8782830df4c73e9/mint/mint.go#L570

So I suspect it is likely something in the splitApi method on the WalletPage that is the source of this bug.

**Comment by callebtc** [comment]
Could verify the same error with the following steps (no swap, with 2 sats): 

- Add two mints (let's call them `mint1` and `mint2` (both are LNbits mints))
- Create invoice in `mint1` for `2 sats` and pay it
- Create invoice in `mint2` for `1 sats`
- Attempt a payment of this `mint2` invoice from `mint1` and reload the browser in the breakpoint first line of `split()` (like above)
- You have `2 sats` in `mint1`.
- Send ecash from `mint1` for `1 sat` 
- Receive this `1 sat` payment
- Run into this error

It does not work if the first invoice is `1 sats` instead of `2 sats` (which is probably because the `2 sats` have to be split before payment and produce change.

**Comment by callebtc** [comment]
If there was a pending invoice, the startup routine would overwrite one mints keys with the keys of the other due to the parallel execution of the method `fetchMintKeys`
