### ISSUE TITLE
use keysets with hex ids when creating proofs to send

### ISSUE THREAD

**Issue by elnosh** [cashubtc/cashu.me#192]
some mints still have non-hex keyset ids. Example [minibits](https://mint.minibits.cash/Bitcoin/v1/keysets) mint has keysets: 
```
"keysets": [
  {
    "id": "9mlfd5vCzgGl",
    "unit": "sat",
    "active": true
  },
  {
    "id": "00500550f0494146",
    "unit": "sat",
    "active": true
  }
```
when creating proofs to send, it generated proofs like such: 
```
"proofs": [
  {
    "amount": 1,
    "secret": "60822b310d5a197d370dcf9948a1cff2b8fd95846d3c55fde2992e3da96d3290",
    "C": "03bea6d0cc5a1d83cced22b3ac00585101d756d0ffaef59642a3904efb046f7cd1",
    "reserved": true,
    "id": "9mlfd5vCzgGl"
  },
 ...
],
"mint": "https://mint.minibits.cash/Bitcoin"
```
using keyset id `9mlfd5vCzgGl` instead of using the hex keyset id `00500550f0494146`

**Comment by prusnak** [comment]
Is this still an open issue? I seem not to have any issues when using that particular mint.

**Comment by elnosh** [comment]
just tried it and yeah it's using the hex keyset id now

**Comment by prusnak** [comment]
I guess let's close this issue then
