### ISSUE TITLE
[BUG] UNITS CONFLICT WHEN PAYING A LNURL REQUEST IN A STABLE MINT

### ISSUE THREAD

**Issue by emtll** [cashubtc/cashu.me#194]
When I am in a USD mint and I want to send to a LNURLp, for example, like the image, the wallet asks me for a USD range but when I input 1 dollar what actually happens is which the wallet continues to interpret as SAT

But if I create an invoice in the destination wallet with the conversion unit, the payment is made according to what was entered in stable, i.e., the problem seems to be only for LNURL requests

![image](https://github.com/user-attachments/assets/251a2869-f323-4e03-a445-e0a28c46e2ec)
![image](https://github.com/user-attachments/assets/de09a923-d04e-438e-be08-d6bebe4be780)

**Comment by lollerfirst** [comment]
#207

**Comment by lollerfirst** [comment]
@callebtc this can be closed.
