### ISSUE TITLE
[Feature request] Restore from seed

### ISSUE THREAD

**Issue by DireMunchkin** [cashubtc/cashu.me#195]
Currently you can copy the seed, which is good, but it'd be better if you could actually restore it as well. Browser storage is relatively easy to wipe by accident, especially if you have your browser set to clear local storage on exit or something like that.

**Comment by DireMunchkin** [comment]
I should also have clarified as I said [here](https://njump.me/nevent1qvzqqqqqqypzpkvxhzjgem6f2r7x9a7u9cxjwl99q46hkk488uy4nvsxt8n37l9vqyfhwumn8ghj7ur4wfcxcetsv9njuetn9uq3xamnwvaz7tm0venxx6rpd9hzuur4vghsqg99qv65w6g52vx8ur9frm8686htf2yht0djx33fp4jmu2dlh8q3jycg4uc4) I can't seem to restore the seed in other clients either. I tried Nutstash and eNuts.

**Comment by callebtc** [comment]
Hi there. Could you please try whether it works with this tool? https://v2alpha.nutstash.app/

I've tried restore multiple times and it always worked for me. I'd love to be able to reproduce this behaviour.

**Comment by DireMunchkin** [comment]
Hey Calle, I was using https://v2alpha.nutstash.app/ when I tested it.

Unfortunately I can't test if for you again because I nuked the wallet I was using by accident. 😅

I'll close this issue for now since I can't reproduce it, thanks anyway.
