### ISSUE TITLE
[Bug] Can Initiate Multi-mint Swap With Single Mint And Lose Funds

### ISSUE THREAD

**Issue by cjbeery24** [cashubtc/cashu.me#20]
Steps to reproduce:

1. User has 2 mints, (Mint 1) with funds and (Mint 2) without funds. User tries to swap from (Mint 2) that has 0 funds to (Mint 1) that already has funds.
<img width="992" alt="Screen Shot 2023-04-24 at 10 45 47 AM" src="https://user-images.githubusercontent.com/6200796/234076089-b1017f67-455b-4ec0-abbf-da6e78fa4322.png">

2. User receives not enough funds error in pop-up
<img width="564" alt="Screen Shot 2023-04-24 at 10 45 57 AM" src="https://user-images.githubusercontent.com/6200796/234076336-70c7a4d5-989a-4376-8b26-c8c82abdacfe.png">

3. User selects (Mint 1) that has funds and proceeds with swap to (Mint 1).
<img width="552" alt="Screen Shot 2023-04-24 at 10 46 18 AM" src="https://user-images.githubusercontent.com/6200796/234076751-8bbb1a94-723e-43ea-8ae1-77a2660384e7.png">

4. Operation succeeded, but now funds are missing from user's wallet.
<img width="1021" alt="Screen Shot 2023-04-24 at 10 52 43 AM" src="https://user-images.githubusercontent.com/6200796/234077024-10719e8a-2152-4431-96c7-96ac1a4f542c.png">

**Comment by callebtc** [comment]
Can you check whether you have a pending invoice (in the invoices tab) and what happens when  you press the refresh button?

**Comment by callebtc** [comment]
@cjbeery24 can you check whether the funds were still available as an invoice you need to redeem?
