### ISSUE TITLE
[Enhancement] Use cashu-ts to handle interactions with cashu protocol

### ISSUE THREAD

**Issue by ebrakke** [cashubtc/cashu.me#22]
There's a lot of code related to interacting with the cashu protocol in the Vue code currently.  Looking through [cashu-ts](https://github.com/cashubtc/cashu-ts), it seems like a great library to use in this cashu wallet implementation.

This will help the cashu wallet code focus more on user interactions, and abstracting away a lot of the nitty gritty protocol level logic.

Going to investigate what kind of a lift it is to start moving this in.

**Comment by callebtc** [comment]
Would be great as it would save a lot of work especially as we update things in the protocol.
