### ISSUE TITLE
Question regarding Pinia

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#23]
Question regarding Pinia: should it store all states of the UI as well? @ebrakke @cjbeery24 

Right now we're using things like `payInvoiceData.show` etc to determine the state of the UI, which are all stored in `WalletPage.vue` but it would be great to have it available everywhere. 

![image](https://user-images.githubusercontent.com/93376500/234221801-a5367fd6-0a8a-414d-824f-4b92aa8a4c84.png)

They are defined in `WalletPage.vue`

![image](https://user-images.githubusercontent.com/93376500/234221910-4f303229-3d93-460f-abf5-6fd208b7254e.png)

Should we make a pinia store for these things?

**Comment by ebrakke** [comment]
Yeah, I think a Pinia store for something like this makes a ton of sense! When I think about frontend state, I generally like to think about all of the different parts of my app that need to share that same state.

For instance, with `mints` there are lots of places that need to know about the current mints:
* The settings menu
* The list of tokens (needs to know active mint)
* The "send ecash" flow (needs to know active mint)
All of those things could be broken out into their own components, and they'll all need to share the same mint state.  To me this means it's a great candidate for a store.

Pulling the invoice data into a pinia store will enable us to refactor some more of the `WalletPage.vue` file into smaller components, and then having those components use the pinia store for all global state.
