### ISSUE TITLE
Locked tokens aren't redeemable in other apps

### ISSUE THREAD

**Issue by thebullishbitcoiner** [cashubtc/cashu.me#238]
Not sure about every other app, but I didn't have success redeeming in 0xchat. 

Here's what I did:

1. Prepended my hex pubkey with "02"   

i.e. 02 + c7617e02242f5853fe5b513d411f19b44ad3f0da95a28d33a9b7e927f255dd2d

2. Created the locked token in Cashu.me

![image](https://github.com/user-attachments/assets/adbeec8d-7187-4da1-9b3e-a922120dc9b2)

3. Tried to redeem in 0xchat but got an error about a missing witness.

![image](https://github.com/user-attachments/assets/6d95764d-c36b-4a90-802d-f8e800ac4e00)

FWIW, I can create locked tokens in both apps and redeem them in the same app without issue.

**Comment by thebullishbitcoiner** [comment]
UPDATE: 0xchat dev has identified this as an issue on their end and will fix in the next update. Will keep you posted.

**Comment by prusnak** [comment]
> UPDATE: 0xchat dev has identified this as an issue on their end and will fix in the next update. Will keep you posted.

Any update?

**Comment by thebullishbitcoiner** [comment]
This issue has been fixed!
