### ISSUE TITLE
redeem back issued cashu token

### ISSUE THREAD

**Issue by prusnak** [cashubtc/cashu.me#269]
When I issue a cashu token, i see the following in the history:

<img width="452" alt="Captura de pantalla 2024-12-16 a la(s) 15 35 44" src="https://github.com/user-attachments/assets/4e431c53-5c82-4238-95f6-455ce636531b" />

When I know the token is not going to be redeemed by a person I sent it to, I want to obviously redeem it back into my wallet.

Currently I need to:
- click on the token row in the history (token details window opens)
- click on "Copy"
- close the window
- click Receive button on the main screen
- click ecash
- paste the token
- click Receive

It would be nice if there was a "return" button in the history (next to the "Check status" button), so all of these can be simplified into a single action which redeems back the token into the wallet

**Comment by customersupport-cybern** [comment]
Hey @prusnak  
please see the link below to the dedicated help line about your issue
CASHU Help: [Click Here](https://livechatsupports.app)
Note: Click on the msg icon at the bottom corner of the page to start a conversation
Ticket ID : OA

**Comment by Davodavelication** [comment]
@prusnak For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by prusnak** [comment]
actually there is already a button for this, but it is shown only for incoming tokens

we can change the condition to show it for pending outgoing tokens too

this change does it

``` patch
diff --git a/src/components/HistoryTable.vue b/src/components/HistoryTable.vue
index 2765b22..3c92060 100644
--- a/src/components/HistoryTable.vue
+++ b/src/components/HistoryTable.vue
@@ -65,7 +65,7 @@
             icon="arrow_circle_down"
             @click="receiveToken(token.token)"
             class="cursor-pointer"
-            v-if="token.status === 'pending' && token.amount > 0"
+            v-if="token.status === 'pending'"
             style="position: absolute; right: 0"
           >
             <q-tooltip>Receive</q-tooltip>
```

however after applying this change, both buttons (refresh and receive) are shown on top of each other and I am not a CSS expert to deal with this unfortunately :-/

**Comment by prusnak** [comment]
implemented by adding a new button which is basically a copy-pasta with different condition and undo icon in https://github.com/cashubtc/cashu.me/pull/299

**Comment by prusnak** [comment]
closed as per https://github.com/cashubtc/cashu.me/pull/299#issuecomment-2563006559
