### ISSUE TITLE
Warn user before deleting a mint

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#27]
Single press on X removes the mint.

**Comment by Taseeeer** [comment]
Hi @callebtc! I would like to work on this issue, please assign it to me.

**Comment by aurorabor** [comment]
This was technically solved with PR #52, but I think its not the most beautiful solution. So you are welcome to submit a PR with a nicer way of warning using one of the dialog boxes. I don't have the time to work on that at the moment.

**Comment by Taseeeer** [comment]
@aurorabor sure let me make a PR.
