### ISSUE TITLE
Remove deprecated "Old token format" switch

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#29]
We don't need the "old format" anymore since all wallets have transitioned to the newest one.

![telegram-cloud-photo-size-2-5352693440812534918-x](https://user-images.githubusercontent.com/93376500/234678596-ee6eaca6-4b99-437b-81fa-e833c07261ae.jpg)

**Comment by Taseeeer** [comment]
@callebtc how does that prompt appears? What are the steps.

**Comment by aurorabor** [comment]
solved in #51
