### ISSUE TITLE
upgrade to @noble/curves for secp256k1

### ISSUE THREAD

**Issue by ebrakke** [cashubtc/cashu.me#35]
Currently, we are using a pre-compiled version of secp256k1. This is the v1 version. I have replaced this in #34 with the npm package on v1.7.

The current recommended way to use the noble libraries is to use https://github.com/paulmillr/noble-curves and https://github.com/paulmillr/noble-hashes

I believe there is breaking change in v2 as we use `secp256k1.Point`, but v2 has replaced this with `ProjectivePoint`.
Not sure what the breaking change is yet, but the app would not work properly using `ProjectivePoint` as a drop in replacement.

**Comment by aekasitt** [comment]
+1

**Comment by aekasitt** [comment]
Big milestone. Congratulations!
