### ISSUE TITLE
Connects to mints, but paid invoices are still pending

### ISSUE THREAD

**Issue by HamishMacEwan** [cashubtc/cashu.me#42]
![image](https://github.com/cashubtc/cashu.me/assets/388061/140664cd-9181-43c1-b843-05b067649092)

It's probably something simple.

**Comment by callebtc** [comment]
Can you press the refresh button?

**Comment by HamishMacEwan** [comment]
I've refreshed the page, and the perfectly adequate refresh icon for both invoices (one per mint)

`Invoice still pending`

is the result.
