### ISSUE TITLE
UI: Animated QRs for more than one ecash token

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#44]
Cashu.me shows a QR code if the sender only sends a single token. We could however use animated QRs that can send multiple tokens, like with what @gandlafbtc has done with Nutstash! Both should be compatible.

@gandlafbtc can you point to a piece of code that we can use for inspiration? 🙏

**Comment by gandlafbtc** [comment]
sure! 

for creating:
https://github.com/gandlafbtc/nutstash-wallet/blob/send-receive/src/comp/elements/BigTokenQR.svelte

for scanning:
https://github.com/gandlafbtc/nutstash-wallet/blob/send-receive/src/comp/elements/ScanToken.svelte

This implementation is somewhat unrefined, but it works pretty well! maybe we can create NUT for this, with the optimal solution/protocol
