### ISSUE TITLE
UI: Show spinner and block button while invoice is created

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu.me#60]
Similar to the Pay invoice Button, we should lock this button and show a spinning wheel indicator when the wallet is waiting for a reply 
![telegram-cloud-photo-size-2-5233274074170510819-y](https://github.com/cashubtc/cashu.me/assets/93376500/c10bd6b4-f138-45fa-9c48-baa2f2b8ae8a)

**Comment by cjbeery24** [comment]
@callebtc Looks like you already did this.
https://github.com/cashubtc/cashu.me/commit/3072652226a4fa8e98fe039f788bb7132adc6198#diff-70c09666cbc9f3343d18beb67f62ba64ca4a00fef1694afbb2bba4453c7acfe2

**Comment by callebtc** [comment]
Thank you, correct!
