### ISSUE TITLE
backup not working

### ISSUE THREAD

**Issue by aurorabor** [cashubtc/cashu.me#73]
I have issues getting my backups back, the token seem to be spent immediately after loading the backup. For testing and developing I usually have multiple instances of the PWA at wallet.cashu.me and locally open and running. But also just having one instance open does not work at the moment. Anyone knows what I am doing wrong?

**Comment by callebtc** [comment]
Hm, I just recently recovered from a backup and it worked quite well. Are you sure the tokens you're recovering aren't spent already?

**Comment by aurorabor** [comment]
yes, did not spend them, it spends my sats directly when I read in the backup
<img width="569" alt="Screenshot 2023-07-09 at 17 17 34" src="https://github.com/cashubtc/cashu.me/assets/115992990/53b928a1-35ef-458d-bd32-d1429dba05fd">
